### ISSUE TITLE
Packet Sniffing Information

### ISSUE THREAD

**Issue by TomFaulkner** [bpennypacker/SenseME-Indigo-Plugin#5]
Were you able to sniff a command to get Whoosh status without using getall? Are there any other commands that you found that aren't in the plugin?

I use your Indigo plugin to start my own library some months ago. It's on my github if you are interested in seeing it.

**Comment by bpennypacker** [comment]
No, I haven't found a Whoosh status command. I never saw one when I was sniffing the traffic between the iPhone app and the fan, so I tried a few combinations of commands based on the names & parameters of others but didn't have any luck.

It just occurred to me that one way of figuring this out may be to look at the iPhone app binary. The 'strings' command might shed some light on the actual commands that the app is capable of sending to the fan. Another approach may be to see if/how to download the fans firmware and examine it in a similar method. More sniffing of the app traffic and/or examining the iPhone app might show where/how it downloads the firmware when an update is available...  If/when I have a little time I might give one or both of these a try.

**Comment by bpennypacker** [comment]
Thank you for that pointer! I had no idea that option was there. I just spent a little time sniffing the network traffic for these and a few other commands. Here are the raw commands for changing the fan direction:

<aa:bb:cc:dd:ee:ff;FAN;DIR;SET;REV>
<aa:bb:cc:dd:ee:ff;FAN;DIR;SET;FWD>

You'll need to replace aa:bb:cc:dd:ee:ff with the MAC address of your fan. Once you do that you should be able to send these as raw commands. Make sure your fan speed is 0 before issuing these commands. The iPhone app warns that it needs to be stopped, but I have no tested to see what happens if you change it wile it's spinning. You may risk damaging the fan if it doesn't know to ignore these commands when the fan is spinning.

I'll see about adding these & some of the other commands I found to the plug-in, but I have no idea when an updated version will be available.
