### ISSUE TITLE
Command for Reverse Fan

### ISSUE THREAD

**Issue by mlamoure** [bpennypacker/SenseME-Indigo-Plugin#7]
Is there a command to enable reverse fan?  If there is, would you be willing to share how to set that up as a raw command, or consider adding it to the available actions?  As winter approaches (northern hemisphere), this is something I'd like to automate!

**Comment by bpennypacker** [comment]
I have never come across such a command, and I doubt one exists. There certainly aren't any settings for it on the wireless remote for the fan or in the iPhone app. All you should need to do, however, is set the mode of the fan to smarter heating or smarter cooling as desired. 

I just realized that I never did look into the "ideal temperature" setting that is in the iPhone app. But the combination of that setting and the smarter heating/cooling settings that this plugin does provide should make your fan reverse direction on its own as it determines the temperature of the room and the optimal airflow for the situation.

I'll look into what it would take to support the ideal temperature setting into the plugin as well.

**Comment by mlamoure** [comment]
Hi there - FYI the setting is in the App, but it's kind of hidden.  

To find it:

Rooms & Devices
Click the fan
"Reverse Fan" option.

However, I was also reading that they dont recommend using this setting, even in the winter.  They suggest using the fan in regular mode, but at a low setting.

**Comment by bpennypacker** [comment]
Thank you for that pointer! I had no idea that option was there. I just spent a little time sniffing the network traffic for these and a few other commands. Here are the raw commands for changing the fan direction:

    <aa:bb:cc:dd:ee:ff;FAN;DIR;SET;REV>
    <aa:bb:cc:dd:ee:ff;FAN;DIR;SET;FWD>

You'll need to replace aa:bb:cc:dd:ee:ff with the MAC address of your fan. Once you do that you should be able to send these as raw commands. Make sure your fan speed is 0 before issuing these commands. The iPhone app warns that it needs to be stopped, but I have not tested to see what happens if you try to change it wile it's spinning. You may risk damaging the fan if it doesn't know to ignore these commands when the fan is spinning.

I'll see about adding these & some of the other commands I found to the plug-in, but I have no idea when an updated version will be available.

**Comment by mlamoure** [comment]
Thanks for this!

**Comment by bpennypacker** [comment]
I just uploaded a new release that now contains triggers & actions for the fan direction, among a handful of other things.
